# Cấu hình prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kong'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '192.168.2.14:8001' ] # Địa chỉ Kong Admin API
