# Cấu hình prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kong'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '10.91.10.38:8001' ] # Địa chỉ Kong Admin API
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '10.91.10.38:9012' ]
  - job_name: 'otp-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '10.91.10.38:9007' ]
